version: '3.7'
services:
  dante:
    build: .
#    image: domorelivelonger/squid
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
        reservations:
          cpus: '0.50'
          memory: 150M
    container_name: dante
    build: 
      context: .
      args:
        - user=x
        - password=x
    ports:
      - "1080:1080"
    restart: always
