version: '3'
services:
  asterisk1:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
        reservations:
          cpus: '0.50'
          memory: 150M
    container_name: asterisk
    restart: always
    build: .
    image: asterisk
    volumes:
      - ./mnt:/mnt
      - ./extensions.conf:/etc/asterisk/extensions.conf
      - ./sip.conf:/etc/asterisk/sip.conf
    network_mode: host
#    ports:
#      - 9060:5060/udp
#      - 10000-20000:10000-20000
    privileged: true

