version: '3'
services:
  pptpd:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 150M
        reservations:
          cpus: '0.50'
          memory: 150M

    container_name: pptpd
    restart: always
    build: .
    image: pptpd
    volumes:
      - ./chap-secrets:/etc/ppp/chap-secrets
    network_mode: host
    ports:
      - 1723:1723
    privileged: true
